resolver: lts-14.10

packages:
  - ff
  - ff-core
  - ff-gtk
  - ff-qtah
  - ff-qml
  - ff-test

extra-deps:
  # ff-core:
  - crdt-10.4
  - github-0.23
  - ron-0.10
  - ron-rdt-0.10
  - ron-schema-0.9
  - ron-storage-0.11
  # - {git: https://github.com/ff-notes/ron.git, commit:, subdirs: []}
  - shellwords-0.1.2.2

  # ff-gtk:
  - gi-gtk-declarative-0.6.0
  - gi-gtk-declarative-app-simple-0.6.0

  # ff-qml:
  - hsqml-0.3.5.1

  # github:
  - binary-instances-1

  # ff-qtah:
  # - hoppy-generator-0.5.2
  # - hoppy-runtime-0.5.1
  # - hoppy-std-0.5.0
  - git: https://gitlab.com/khumba/hoppy.git
    commit:
      45dded1e21c29409a09eb88ec92bd33b4f6ed0f3
      # 0.5.1 + Compatibility with GHC 8.6, Cabal 2.4
    subdirs: [generator, runtime, std]
  - git: https://gitlab.com/cblp/qtah.git
    commit: 63db0e40c8d1509ac80f82b4bf8860225058a7b6  # 0.6.0 + master + fixes
    subdirs: [qtah, qtah-cpp, qtah-generator]

docker:
  enable: false
  image: ff-ubuntu-16.04

flags: {qtah-cpp: {qt5: true}}

nix:
  packages: [zlib qt5.qtbase gtk3 gobject-introspection]
